spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cobwebsDB
    username: admin
    password: 1234
    name: cobwebsDB
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
  security:
    user:
      name: admin
      password: p@$$w0rd
